import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "./_components/_layout/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col">
        <div className="flex flex-row h-full">
          <div className="w-16 items-center pl-1 justify-center h-full">
            <Sidebar />
          </div>
          <div className="flex-1 m-1 rounded-md bg-secondary backdrop-blur border border-white/30 shadow-lg">{children}</div>
        </div>
      </body>
    </html>
  );
}
